#!/bin/sh
#
# mongodb-mgrast      init file for starting up the MongoDB server for the $tenant 
#
# chkconfig:   - 90 10
# description: Starts and stops the MongDB daemon that handles all \
#              mgrast database requests.

tenant="mgrast"           # TENANT

. /etc/rc.d/init.d/mongodb-functions

## END OF LINE ##
