#!/bin/sh
#
# mongodb-kbase      init file for starting up the MongoDB server for the $tenant
#
# chkconfig:   - 90 20
# description: Starts and stops the MongDB daemon that handles all \
#              kbase database requests.

tenant="kbase"           # TENANT

# Source all the mongodb startup code - this file JUST sets the tenant we are working for
. /etc/rc.d/init.d/mongodb-functions

## END OF LINE ##
